name: Frontend CI

on:
  push:
    branches:
      - Development
      - Feature
      - frontend-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive build output
        run: |
          mkdir -p ./build_output
          echo "Test file" > ./build_output/test.txt
          tar -czf build_output.tar.gz ./build_output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: build_output.tar.gz