name: Frontend CI Pipeline

on:
  push:
    branches:
      - testingBranch

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: |
          npm install --save-dev jest jest-html-reporter
          mkdir -p test_results coverage artifacts
          npx jest --coverage --outputFile=test_results/junit_report.json --json
          cp coverage/lcov-report/index.html artifacts/test-report.html
          cp -r coverage/lcov-report artifacts/htmlcov

      - name: Inject last updated timestamp into dashboard
        run: |
          TIMESTAMP=$(TZ="Europe/Copenhagen" date +"%Y-%m-%d %H:%M CET")
          echo "<html><body><h1>Last updated: $TIMESTAMP</h1></body></html>" > artifacts/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: artifacts/*

  deploy:
    needs: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifacts
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
