name: Frontend CI Pipeline

on:
  push:
    branches:
      - Development
      - Feature
      - frontend-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Disable Treating Warnings as Errors
        run: |
          echo "CI=false" >> $GITHUB_ENV  # Explicitly set CI to false

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: react-build
          path: ./build