name: Frontend CI Pipeline

on:
  push:
    branches:
      - testingBranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Run tests with HTML report
        run: |
          npm install jest-html-reporter
          mkdir -p artifacts/test-report
          npx jest --ci --reporters=default --reporters=jest-html-reporter
        env:
          JEST_HTML_REPORTER_OUTPUT_PATH: ./artifacts/test-report/test-report.html

      - name: Generate code coverage
        run: |
          npx jest --coverage --coverageReporters=html
          mv coverage/lcov-report artifacts/htmlcov || echo "No htmlcov folder"

      - name: Inject last updated timestamp into dashboard
        run: |
          TIMESTAMP=$(TZ="Europe/Copenhagen" date +"%Y-%m-%d %H:%M CET")
          sed -i "s|{{LAST_UPDATED}}|$TIMESTAMP|" Test/ReportDashboard/index.html

      - name: Copy dashboard to artifact folder
        run: |
          mkdir -p artifacts
          cp Test/ReportDashboard/index.html artifacts/index.html

      - name: Upload frontend test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: artifacts/*

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifacts
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
